### ISSUE TITLE
Start Deprecation and Removal of Selenium2Library (deep) references/package

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#1826]
As noted in the v6.1.0 release notes .. "Due to the issues around upgrading packages and the simple passage of time, it is time to depreciate and remove the Selenium2Library package." This issue will track the task and progress of the depreciation.

**Comment by humbienri** [comment]
;) Depreciation or deprecation is it?

**Comment by emanlove** [comment]
Oh .. darn. Now I am trying to remember if I was saying the right word that entire meeting. Thanks for noting this @humbienri  Corrected.

**Comment by humbienri** [comment]
I was only kidding! I don't do much RF work at all anymore but I still get the GH emails about it. Ya'll are a great bunch of folks! One of the best online communities I've EVER seen. Kudos!

**Comment by emanlove** [comment]
Well we definitely don't want to devalue it over time (depreciate) but instead we want to discourage current usage, encourage people instead to use SeleniumLibrary directly and plan a removal (deprecate). So I think you got it right. And thanks for the kind words :)

**Comment by humbienri** [comment]
Actually, I am surprised to see S2L still around! Like I said, it's been years since I used RF-anything and even back then I thought S2L needed to go and its usage should have been highly discouraged. So I do think you are doing the right thing; alleviating some of the burden from ya'll's backs. Best of luck Ed!

**Comment by emanlove** [comment]
Some initial thoughts on the steps to Start Deprecation and Removal of Selenium2Library (deep) references/package
### Stage 1

- [ ] - Make announcements everywhere (Slack, Forum, LinkedIn, Twitter, Facebook, email lists) ..
- [ ] - Add note to install saying this is deprecated and will be removed in the near future(? specifics)
- [x] - Move "Versions" and "History" sections of README.rst to VERSIONS.rst referencing this file.
- [x] - Remove Selenium2Library instructions moving them to this new versions.rst file.
- [x] - Update setup.py
- [ ] - [It may be possible to get the list of projects that use Selenium2Library from GitHub. Last check Used By shows 1,159 repositories so it is not clear what one would do with this information. And how to discern out which repos are old. I know this can be done but the amount of work to do that now might be questionable in terms of ROI]
- [ ] 

### Stage 2

- Add note to install saying this will be removed on xx/xx/2023 date

### Stage 3

- Add error to install causing install to fail

### Stage 4 (?)

- Deal with cleanup mess

**Comment by emanlove** [comment]
We have started some documentation changes which have been merged into master for the upcoming v6.4.0 release. One last change I wanted to get in was provide from the SeleniumLibrary side a warning if it was wrapped by Selenium2Library but having some issues with my IDEs. I am going to open another issue for that so that we can close this and recognize some work has been done to deprecate Selenium2Libary.
