### ISSUE TITLE
1.7.3 Release checklist

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#478]
- [x] Removes dependency on latest for `RobotNotRunningError` #476, ~~#466~~
- [x] Fixes screenshot links in the logs being broken in some conditions ~~#460~~
- [x] Add named keys to `Press Key` ~~#474~~ 

That's in this release thus far. Does anything else need to be added? I don't necessarily want to rush this out, but I do want it get it out before too long. #466 really needs to be pushed out. 

Thoughts or suggestions are welcome. @emanlove, anything to add or detract?

**Comment by HelioGuilherme66** [comment]
I am working on a Press Keys keyword. But it is not ready (some tests fail) [https://github.com/HelioGuilherme66/robotframework-selenium2library/commit/3b46328967bf86ab28ab3411aa96e3f6a5ec0dc4]

Maybe someone could make a review to see if would enter in 1.7.3?
Thanks.

**Comment by just-be-dev** [comment]
I'll work with you on that @HelioGuilherme66, but if it's not really ready I don't think we should hold up 1.7.3 for it.

I really want to get this release out today to fix the broken backwards compatibility.

**Comment by HelioGuilherme66** [comment]
There is now a PR for Press Keys. I changed CHANGES.rst because there was repeated entries. This is causing conflicts. I marked Press Keys for 1.7.3 because it should go as experimental, and I would like for users to try it (since there could be side effects, that should be well documented).

**Comment by just-be-dev** [comment]
1.7.3 released as of d4560b5.
