### ISSUE TITLE
List of PRs to merge for Python 3.x compatibility

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#658]
Merger should do them in this order:
- [x] 1. Unify print() usage ... #684 
- [x] 2. fixes imports to be compatible with Python 2.7 and 3.3+ ... #653 - Closed without merge
- [x] 3. Fix remaining print ... #654 - Closed without merge
- [x] 4. Adds Travis configuration for Python 3.4 and 3.5 ... #657  - Closed without merge
- [x] 5. Fix running unit tests py3 ... #656 - Closed without merge
- [x] 6. Modified how Travis CI is used in the project #716 (merged)
- [x] 7. Clean up run_unit_tests.py ... #662 (merged), #693 - Closed without merge
- [ ] 8. Fix running unit tests py3 ... #720 and also #747
- [x] 9. Fixes installer for both Python 2.7 and 3.x. #718 (merged)

**Comment by SebCorbin** [comment]
Just leaving it here, I've been using https://github.com/HelioGuilherme66/robotframework-selenium2library/releases/tag/v1.8.0b3 and it works really well, thank you!

**Comment by HelioGuilherme66** [comment]
Thanks for letting us know. We will have an official release, hopefully before 2017 ;).

**Comment by aaltat** [comment]
Do we still need this or can we close it?
