### ISSUE TITLE
Cleanup and enhance keyword documentation

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#925]
Issue #924 covered enhancing generic library documentation. Similar problems as described in it also in the actual keyword docs. Would be great to go through them too before SL 3.0 final.

**Comment by pekkaklarck** [comment]
Part of this issue is going through open issue related to documentation and see can they be fixed at the same time.

**Comment by pekkaklarck** [comment]
This issue has taken ages to get done because there are so many keywords and some of their docs require a total rewrite. There have also been several nasty surprises with functionality, requiring us to do fixes such as #933, #966, #923, #958 and #942. I hope we've uncovered most of these surprises and it doesn't take too much time to finish this.

Below is a list of files under `src/SeleniumLibrary/keywords/` with files already cleaned up marked:

- [x]  `alert.py`
- [x]  `browsermanagement.py`
- [x]  `cookie.py`
- [x]  `element.py`
- [x]  `formelement.py` (PR #984)
- [x]  `frames.py`
- [x]  `javascript.py` (PR #984)
- [x]  `runonfailure.py`  (PR #984)
- [x]  `screenshot.py` (PR #986)
- [x]  `selectelement.py` (PR #989)
- [x]  `tableelement.py` (PR #992)
- [x]  `waiting.py`  (PR #984)
- [x]  `window.py`

**Comment by pekkaklarck** [comment]
Issue #188 proposed adding examples to `Wait For Condition`. Sounds like a good idea to me but I don't have any good examples in my mind. Any ideas @aaltat or others?

**Comment by pekkaklarck** [comment]
All keyword docs have now been reviewed and cleaned up, but not all PRs with the changes (see [my comment above](https://github.com/robotframework/SeleniumLibrary/issues/925#issuecomment-342012257)) have yet been merged. Once they are, we need to still regenerate the docs and see there are no obvious problems. Otherwise this issue is about to be done.

**Comment by pekkaklarck** [comment]
This issue is finally about to be ready. Still need to review the generated docs and fix possible problems. The docs can be found from http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html

**Comment by aaltat** [comment]
The documentation looks OK for me. Closing the issue.
